from .load_gif_as_video_node import (
    NODE_CLASS_MAPPINGS as _GIF_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _GIF_NAMES,
)
from .loop_video_node import (
    NODE_CLASS_MAPPINGS as _LOOP_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _LOOP_NAMES,
)

NODE_CLASS_MAPPINGS = {**_GIF_CLASSES, **_LOOP_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_GIF_NAMES, **_LOOP_NAMES}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
