[project]
name = "load-gif-as-video"
version = "0.1.4"
description = "Loads an animated GIF/APNG/WEBP as a VIDEO stream, loops any VIDEO with variable playback speed, and saves a VIDEO or image batch back out as an animated GIF with a full set of color quantizers and dithering filters"
readme = "README.md"
license = {text = "MIT license"}
requires-python = ">=3.10"
classifiers = []
dependencies = [
]

[project.urls]
Repository = "https://github.com/id-fa/ComfyUI-LoadGifAsVideo"

[tool.comfy]
PublisherId = "id-fa"
DisplayName = "Load GIF as Video"
Tags = []
Repository = "https://github.com/id-fa/ComfyUI-LoadGifAsVideo"
includes = []
